### ISSUE TITLE
Ayuda con pifba

### ISSUE THREAD

**Issue by elk9999** [aikoncwd/aikoncwd-rpi-mediacenter#10]
Hola ,tengo un problema con el emulador fba, cuando juego kof para seleccionar los personajes en random,como todos saben hay q presionar el start para eso, la cosa es q apreto start por 3 segundos y entra a la configuracion de hardware del juego. Hay alguna configuracion para pifba para asignar algun hotkey o deshabilitarlo. Gracias y excelente trabajo con tu imagen, muy bien configurado todo y facil de usar.

**Comment by aikoncwd** [comment]
No utilizo muy a fondo ese emulador, te dejo link oficial de la wiki son toda su información. Quizás puedas encontrar lo que buscas [aqui](https://github.com/retropie/retropie-setup/wiki/FinalBurn-Alpha).

Puedes probar a utilizar otro emulador d eneogeo en lugar de pifba, por ejemplo (GnGeo-Pi), (PiFBA), (lr-fba), (lr-fba-next). Si encuentras la solución, agradecería que me avises para ponerlo en el tutorial :)

**Comment by elk9999** [comment]
Gracias apenas tenga tiempo lo reviso y comento a ver que solucion hay.Saludos desde Argentina
