### ISSUE TITLE
Error en imagen para BerryBoot

### ISSUE THREAD

**Issue by xusmen69** [aikoncwd/aikoncwd-rpi-mediacenter#13]
Hola, he realizado los pasos necesarios para preparar la imagen para instalarlo en berry boot (lo he hecho con mas distros), sin errores, y al arrancar no aprecen errores y se queda en la imagen de garlic-dog, ¿algo que se me pueda estar escapando?

**Comment by aikoncwd** [comment]
Creo que mi imagen no es compatible con berryboot :(
