### ISSUE TITLE
Freeze when trying to show desktop

### ISSUE THREAD

**Issue by mjuarezm** [aikoncwd/aikoncwd-rpi-mediacenter#14]
Cuando intento mostrar el escritorio (para obtener una shell), ya sea con el menu de salida o el de excritorio xfce en el menu de herramientas, el sistema se congela (nisiquiera puedo abrir una tty con alt+f#). Como puedo obtener una consola despues de iniciarse kodi (si es posible sin tener que loguearme)?

**Comment by aikoncwd** [comment]
Pulsa el icono inferior izquierdo (en kodi) para `salir`. Aparecerás automáticamente en la consola. Otra opción sería lanzar una sesión SSH contra la raspberry, desde otro PC.
