### ISSUE TITLE
No arranca retropie despues de actualizar

### ISSUE THREAD

**Issue by Razak99** [aikoncwd/aikoncwd-rpi-mediacenter#15]
Hola, despues de actualizar todo retropie (modulos incluidos) no me arranca. Desde kodi lo selecciono, sale pantalla negra y acaba volviendo a kodi. Es porque no se puede actualizar? O porque algo ha quedado mal? Desde la consola ejecuto emulationstation y me dice q no deberia ejecutarse como root...

Gracias por adelantado!

**Comment by aikoncwd** [comment]
emulationstation tiene una restricción para evitar ser ejecutado como root. Si actualizas retropie, esa restricción se activa (por eso no te funciona). Soluciones:

- Vuelve a grabar la imagen original y no actualices
- Edita el fichero `/usr/bin/emulationstation` y elimina la segunda línea, para eliminar la restricción de root.

**Comment by albertoner81** [comment]
Hola, lo primero, muchisimas gracias por todo el curro que te pegas.

Y lo segundo, ¿a que línea te refieres?, porque la he eliminado y no me arranca, ahora tengo retropie 4.2

Muchas gracias

**Comment by alvmoran** [comment]
albertoner81 por favor, puedes indicar que archivo de emulstation y que lineas se debe eliminar.

Gracias.

**Comment by albertoner81** [comment]
Edita el fichero /usr/bin/emulationstation lo pone aikoncwd unos post más arriba.

Salidos digo saludos.

**Comment by alvmoran** [comment]
Gracias y perdona mi torpeza, pero en retropie 4.2 para raspberrypi 3, mediante red no veo ese fichero.

**Comment by albertoner81** [comment]
Yo lo edité desde raspbian y no te preocupes yo soy más torpe que tú.

**Comment by alvmoran** [comment]
Por favor, podríais idicarme las lineas a eliminar.
A ver si localizo desde conexion ssh que archivo es el que hay que editar.
Ya que no tengo usr/bin
Solo tengo parecido
Config/emulationstation y alli varios archivos pero su codigo solo hace referencia a bitones de los mandos.

**Comment by albertoner81** [comment]
Pues ni idea tío, ahí me pillas. Lo siento mucho.
