### ISSUE TITLE
Abrir Terminal en Retropie

### ISSUE THREAD

**Issue by jumperV** [aikoncwd/aikoncwd-rpi-mediacenter#17]
Buenas! 
He estado probando la imagen que subiste, el mediacenter va bastante bien y el escritorio tambien, la cosa es al entrar en retropie, generalmente el terminal una vez dentro de retropie se abre pulsando F4 pero al hacerlo en esta imagen me saca al mediacenter, hay alguna combinación de botones para abrir el terminal? u otra forma de abrirlo dentro de retropie? 
Gracias de antemano

**Comment by aikoncwd** [comment]
No, en ésta imagen no se puede acceder a la consola (terminal) pulsando F4. Si necesitas trabajar en la consola desde RetroPie te aconsejo salir del mediacenter (Kodi) y aparecer en el terminal. Otra opción es acceder al terminal desde un dispositivo externo (desde tu portatil, PC o Smartphone) usando SSH. Hay aplicaciones de terminales SSH para android/iphone muy buenos!
