### ISSUE TITLE
Terminal y mediacenter

### ISSUE THREAD

**Issue by jumperV** [aikoncwd/aikoncwd-rpi-mediacenter#18]
Gracias por la velocidad en responder! Me ha quedado claro, entonces si por ejemplo quiero meter un juego manualmente desde la terminal, puedo hacerlo desde el escritorio que tiene la imagen o mediante ssh. 
Otra duda que tengo es, con kodi en si mismo, no se si es cosa mia pero le veo algo lento a veces entre menus de busqueda y tengo algun problema para repreducir peliculas, por ejemplo el puglin "quasar" le escojo para reproducir pero sale un mensaje diciendo que quasar se cerro y con los otros dos puglins no consigo ver peliculas,se queda cargando sin llegar a inciar el video o da error de reproducción.
Como ultima pregunta, si estas viendo una pelicula/serie, esta se pone al salir como fondo, como hago para cerrarla del todo?
Gracias de nuevo.

Edit:
Todos los problemas solucionados, ya consegui meter juegos en retropie y solucione el problema con la reproducción de video. Ultima duda, como se cambia la imagen de inicio?

**Comment by aikoncwd** [comment]
La imagen de inicio puedes editarla con el fichero '/etc/splash.jpg' si no recuerdo mal
