### ISSUE TITLE
No funciona el streaming de Steam con moonlight.

### ISSUE THREAD

**Issue by lubinos** [aikoncwd/aikoncwd-rpi-mediacenter#19]
Buenas, al intentar hacer streaming de mi biblioteca de Steam desde mi pi3, me sale en bucle el siguiente mensaje:

Waiting for IDR frame.

He buscado por Google y he visto un hilo de github que dice que se arregla en la versión 2.2.2 de moonlight-embedded.

¿Cómo puedo saber que paquete hay instalado en tu imagen?
¿Cómo puedo actualizar el paquete?

**Comment by lubinos** [comment]
Se me olvido poner el enlace al hilo de github

https://github.com/irtimmer/moonlight-embedded/issues/424

**Comment by lubinos** [comment]
Actualizo para comentar que solucione el problema actualizando a la versión 2.2.2, para ello desde consola ejecute los siguientes comandos:

apt-get update
apt-get install moonlight-embedded

Tras realizar la instalación solo tuve que eliminar el dispositivo desde shield en mi pc y volver a enlazarlos (pair)

**Comment by aikoncwd** [comment]
@lubinos disculpa mi demora en contestar, me alegra saber que lo has solucionado. Un saludo!
