### ISSUE TITLE
carga de roms

### ISSUE THREAD

**Issue by joakini10** [aikoncwd/aikoncwd-rpi-mediacenter#25]
Hola, me gustaríoa saber que romset es el correcto a utilizar con la distribucion de mame que incluyes en este Media Center. Muchas Gracias

**Comment by J3DAH** [comment]
Si, me sumo, por favor!

**Comment by aikoncwd** [comment]
Aquí tenéis la [wiki oficial](https://github.com/RetroPie/RetroPie-Setup/wiki/Managing-ROMs)

Dependiendo el emulador utilizado, podéis usar los romsets de la tabla, pero yo recomiendo 0.37b5

**Comment by picapaujulen** [comment]
Cual sería la indicada para play station one??muchas gracias
