### ISSUE TITLE
Error al intentar entrar a la configuración RetroPi

### ISSUE THREAD

**Issue by intro65** [aikoncwd/aikoncwd-rpi-mediacenter#26]
Hola,
Grabe la imagen en una micro SD Class 10 con Win32DiskImager y todo correcto solo que cuando quiero entrar a la configuración de RetroPi, al momento que quiere cambiar la interfaz a modo consola me manda a pantalla en negro y ya no puedo hacer nada de vez en cuando aparece el arco iris de carga.

Alguna idea ? 

Saludos

**Comment by aikoncwd** [comment]
Creo que se te ha grabado mal la imagen (o tienes la microSD corrupta). Prueba a formatear y grabar la iso de nuevo.
