### ISSUE TITLE
Alternativa para cargar imagen en macOS

### ISSUE THREAD

**Issue by jagarciavi** [aikoncwd/aikoncwd-rpi-mediacenter#27]
Hola, estuve intentando cargar la imagen en macOS con el comando que tienes en el README, sin conseguir que encendiera la imagen en mi Raspberry Pi.

Encontré esta herramienta gráfica llamanda [ApplePi-Baker](http://www.tweaking4all.com/software/macosx-software/macosx-apple-pi-baker/). Muy recomendada para novatos.

Un saludo.

**Comment by aikoncwd** [comment]
Gracias por la info. Lo añadiré al readme :)
