### ISSUE TITLE
Mame no funciona

### ISSUE THREAD

**Issue by joviwap** [aikoncwd/aikoncwd-rpi-mediacenter#28]
No consigo hacer funcionar ninguna ROM de MAME, he intentado de diferentes fuentes y en ambos emuladores pero no hay forma. Se supone que puedo apretar al botón A para entrar en la configuración pero no hace nada :(

**Comment by aikoncwd** [comment]
El emulador de MAME es algo especial. Primero de todo necesitas buscar e instalar el fichero **bios** correcto. Luego tienes que utilizar un romset específico para la versión de MAME que estés utilizando. Por ejemplo mame4all utiliza roms de la versión 0.37b5. Tienes el listado [aquí](https://github.com/retropie/retropie-setup/wiki/Managing-ROMs). Tienes más información sobre los emuladores de MAME [aquí también](https://github.com/RetroPie/RetroPie-Setup/wiki/MAME)
