### ISSUE TITLE
Dist-upgrade

### ISSUE THREAD

**Issue by Yuyiroquai** [aikoncwd/aikoncwd-rpi-mediacenter#29]
Estaba siguiendo tu manual para instalar Pi-hole en Aikoncwd v6. Tras lanzar el comando "sudo apt-get dist-upgrade" (previamente ejecuto: update y upgrade) y reiniciar, tengo un par de fallos:

- Si inicio la raspberry con el receptor wireless del mando Xbox 360 se muestra el siguiente mensaje e inicia kodi, si le doy a salir, se queda estancado en el mismo y no inicia el terminal a menos que haga ctrl+alt+F7, ctrl+alt+F8 y ctrl+alt+F1. Ahí me muestra el terminal normal y corriente
![img_20161129_002451](https://cloud.githubusercontent.com/assets/24210247/20690879/7b467602-b5cd-11e6-921e-17a48557e04e.jpg)

- Si inicio sin tener conectado el receptor wireless de Xbox 360, arranca todo bien, me pide usuario y contraseña pero inicia kodi a los 5 segundos mas o menos, si salgo de kodi e introduzco usuario y contraseña vuelve a iniciar kodi. 

Si vuelvo a salir, lanzo el comando "exit" y vuelve a pedirme usuario y contraseña
![img_20161129_002727](https://cloud.githubusercontent.com/assets/24210247/20690880/7b470ce8-b5cd-11e6-8738-301546ea2d8e.jpg)

PD: Soy novato en usar linux y cualquier distribución

**Comment by aikoncwd** [comment]
Formatea y vuelve a grabar la imagen, esta vez no hagas ningún `update, upgrade, dist-upgrade`. La imagen está preparada para funcionar con una versión de binarios concreta, si actualizas es normal que algunas cosas dejen de funcionar.
