### ISSUE TITLE
Nintendo64

### ISSUE THREAD

**Issue by jotab24** [aikoncwd/aikoncwd-rpi-mediacenter#30]
Primero agradecerte el trabajo, yo lo tenia a medio hacer y un amigo me comentó tu imagen y ed espectacular.

Tienes alguna config para n64 en rp3?? Los juegos van lentos y no se si es posible mejorarlo un poco.

saludos

**Comment by aikoncwd** [comment]
Yo no tengo ninguna config especial, pero te dejo un articulo de la wiki oficial de RetroPie, a ver si tienes suerte:

https://github.com/RetroPie/RetroPie-Setup/wiki/Optimization-for-Nintendo-64
