### ISSUE TITLE
emustation should not be run as root

### ISSUE THREAD

**Issue by gazpachio** [aikoncwd/aikoncwd-rpi-mediacenter#33]
Hola, ayer instale aikoncwd y me dejaba entrar bien a emustation pero no tenia ninguna rom o yo no sabia usarlo y hoy al entrar despues de meter una rom me dice emustation should not be run as root....

Alguna idea de como arreglarlo?

**Comment by aikoncwd** [comment]
Al parecer has actualizado RetroPie desde alguna opción del menú de sistema, por eso te aparece ese error. Te recomiendo que formatees la SD e instales la imagen de nuevo (ésta vez sin actualizar nada más).
