### ISSUE TITLE
Instalar en beryboot.

### ISSUE THREAD

**Issue by maeartin** [aikoncwd/aikoncwd-rpi-mediacenter#36]
Hola. Primero que nada darte las gracias por el curro que te has pegado. He estado un tiempo usandolo y va muy fino. Me gustaria preguntarte si existe algun modo de instalarlo en berryboot ya que en una sd tengo veryboot y me gustaría poder tenerlo ahi.

Un saludo

**Comment by aikoncwd** [comment]
Hasta donde yo se, no se puede instalar junto a Berryboot. Se trata de un sistema raspbian completo. Puedes intentar utilizar cualquier guía standar para berryboot, pero no te aseguro que te vaya a funcionar o te salgan algunos problemas o incompatibilidades
