### ISSUE TITLE
Install Addons Vu+ enigma 2 client

### ISSUE THREAD

**Issue by galastico** [aikoncwd/aikoncwd-rpi-mediacenter#38]
Hola, estoy instando instalar este addon  me es imposible, todo lo que he probado me da error. 

¿alguna ayuda?

Gracias

**Comment by aikoncwd** [comment]
No conozco ese addon, quizás lo recomendable es que preguntes en el foro/github del creador de ese addon.

**Comment by galastico** [comment]
Gracias por la respuesta. 

Ya he dado con la solución, instalando desde el terminal ya lo coge sin problema. 

Un saludo
