### ISSUE TITLE
Programar reinicio automatico

### ISSUE THREAD

**Issue by jotab24** [aikoncwd/aikoncwd-rpi-mediacenter#41]
Como puedo programar un reinicio automatico??

**Comment by aikoncwd** [comment]
Puedes hacer uso de **cron**; desde una consola escribe `crontab -e`, sitúate al final del fichero y añade una nueva línea, por ejemplo:  

> 0 7 * * * /sbin/reboot

Ésa línea en cron ejecutarà el proceso `/sbin/reboot` cada día, a las 07:00am.

**Comment by jotab24** [comment]
muchas gracias funciona de maravilla
