### ISSUE TITLE
¿Como puedo cambiar el fondo del perro al arrancar el sistema kodi por otro?

### ISSUE THREAD

**Issue by Grondoval** [aikoncwd/aikoncwd-rpi-mediacenter#43]
Me gustaría poder cambiar el fondo al arrancar el sistema operativo por otro. Se que el fichero se llama splash.jpg pero, ¿donde estaría ubicado el original para cambiarlo por un fondo mío?

**Comment by aikoncwd** [comment]
Puedes buscarlo usando el comando `find \ | grep splash`, pero si la memoria no me falla está en `/etc/splash.jpg`
