### ISSUE TITLE
Algunas dudas con emuladores o juegos en RetroPie

### ISSUE THREAD

**Issue by Grondoval** [aikoncwd/aikoncwd-rpi-mediacenter#44]
-¿Es posible poner como emulador en emulationstation la pista de baile Stepmania? He visto una alternativa que se llama pydance pero no tengo nociones suficientes en linux para probarlo. 

-He configurado OpenBOR y he descomprimido los .pak pero aunque aparecen en el listado no parecen ejecutables porque se vuelve al menú de RetroPie, ¿hay que hacer alguna configuración o pasos específicos?

-Me aparece un menu en RetroPie llamado Arcade -> mame 2003 y ahí tengo las bios. Como podría hacer para que este menú no apareciera en el menú principal de RetroPie?

**Comment by aikoncwd** [comment]
- Supongo que es posible, pero no conozco ese juego ni pydance. Tendría que investigar como integrarlo todo en el mismo sistema.

- Tampoco conozco OpenBOR ni se si es compatible con RPi3, RetroPie, etc... quizás puedas conseguir algo de ayuda en el foro de OpenBOR.

- Cuando añades un fichero al directorio de un emulador, éste aparecerá visible en el menú. Si no quieres que aparezca el emulador no pongas ningún fichero en su carpeta. Otra opción sería editar el fichero `es_systems.cfg` y cambiar la propiedad visible. [Aquí tienes un reddit que hablan de ello](https://www.reddit.com/r/RetroPie/comments/2wskvq/hiding_emulators_in_emulation_station/)
