### ISSUE TITLE
Kodi 17 + addon cine

### ISSUE THREAD

**Issue by jneivil** [aikoncwd/aikoncwd-rpi-mediacenter#48]
Hola. Va a ser posible disponer de kodi 17 y un nuevo addon de cine https://www.kodimania.com/viewtopic.php?t=8463 ????

Gracias

**Comment by aikoncwd** [comment]
Hola @jneivil 

Estoy esperando a que actualicen el repo con Kodi v17 (yo creo que éste fin de semana estará). Espero disponer de tiempo suficiente para actualizar la imagen rápidamente. La idea es actualizar la imagen v7 con Kodi v17. Ese addon no lo conozco, lo revisaré y si lo veo útil lo añadiré.

De todas formas, tú siempre puedes ampliar los addons manualmente e instalarlo si lo deseas. Un saludo
