### ISSUE TITLE
Error En Pantalla Monitor

### ISSUE THREAD

**Issue by Crakxploit** [aikoncwd/aikoncwd-rpi-mediacenter#5]
Error Al Iniciar En Monitor De PC A Resolución 1366x768, Se Queda Totalmente En Negro, Eh Probado Otras Versiones Tales Como Retropié y Inicia Correctamente, E' Seguido Todas Tus Indicaciones Al Pie De La Letra, Me Gustaria Saber Como Arreglo Eso, Ya Que Tu Versión De Mediacenter Es Mucho Mejor

MAS INFO: Utilice "SDFormatter" Y Todo Correcto, Grabe La Imagen Con "Win32DiskImager" Pero A la Hora De Iniciar Mi Raspberry Pi 3 Se Queda Totalmente En Negro Y Cada 5-10 Segundos Se Ve La Imagen En Arcoiris Como Si Andara Algo Mal, Utilizo un Monitor Samsung SyncMaster E1920, La Coneccion Es Mediante DVI To HDMI

**Comment by aikoncwd** [comment]
Realiza las siguientes pruebas:
1. Vuelve a grabar la SD, es posible que se haya grabado mal
2. Prueba a conectar la RPi en otro TV o monitor, solo para comprobar si arranca correctamente

**Comment by query10** [comment]
Hola, me ha pasado lo mismo con un monitor hdmi, en la tele funciona perfecto.

Muchas gracias por el aporte me has ahorrado muchas horas.

**Comment by aikoncwd** [comment]
Habéis podido solucionar el problema? Os puedo ayudar en algo más?
