### ISSUE TITLE
problemas con quasar en aikoncwd v6

### ISSUE THREAD

**Issue by Tuly21** [aikoncwd/aikoncwd-rpi-mediacenter#51]
Buenas ante todo gracias por compartir este gran proyecto, y bueno yendo al grano solo queria preguntar que cuando uso pelisalacarta y para reproducir un torrent mediante quasar me ocurre que empieza ha hacer el prebuffering antes de comenzar la reproduccion muy rapido hasta el 40% del prebuffering y posterior la velocidad baja quedandose en 30 kb/s y teniendo pequeños picos de velocidad pero mayormente quedandose a esa velocidad no se el motivo y asi no puedo reproducir las peliculas mediante torrents.

gracias de antemano espero me puedas ayudar

**Comment by aikoncwd** [comment]
Que conexión de internet tienes? Tienes la RPi configurada por cable o por Wifi? Tienes los puertos del router abiertos contra la IP de la RPi? Desde que servidor estás visualizando los torrents?

**Comment by Tuly21** [comment]
Buenos dias mira ls conexion que tengo es fibra optica 200 megas la rpi 3
modelo b la tengo conectada por cable los puertos que he abierto son los de
quasar, torrents, plexus y demas. Las pelis las intento ver por newpct1.
Ademas decirte estoy intentando que quasar almacene el archivo temporal que
genera en un pendrive pero me va muy lento como te decia y tambien me
ocurre que el torrenter no se puede actualizar.

Gracias de antemano.


El 20 feb. 2017 9:50, "AikonCWD" <notifications@github.com> escribió:

Que conexión de internet tienes? Tienes la RPi configurada por cable o por
Wifi? Tienes los puertos del router abiertos contra la IP de la RPi? Desde
que servidor estás visualizando los torrents?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aikoncwd/aikoncwd-rpi-mediacenter/issues/51#issuecomment-281020413>,
or mute the thread

**Comment by aikoncwd** [comment]
Posiblemente el cuello de botella lo tengas al intentar guardar el torrent en local. Prueba xbmctorrent a ver si te va mejor o elimina la opción de guardar el temporal en el USB.

**Comment by Tuly21** [comment]
Y entonces pregunto si no le indico ningun dispositivo externo donde se
guarda el temporal y la otra pregunta es si despues de parar la
reproduccion se elimina ese temporal q imagino estara en la sd en algun
sitio.

Gracias

El 21 feb. 2017 16:57, "AikonCWD" <notifications@github.com> escribió:

Posiblemente el cuello de botella lo tengas al intentar guardar el torrent
en local. Prueba xbmctorrent a ver si te va mejor o elimina la opción de
guardar el temporal en el USB.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aikoncwd/aikoncwd-rpi-mediacenter/issues/51#issuecomment-281386310>,
or mute the thread

**Comment by Tuly21** [comment]
Otra pregunta porque torrenter no se puede actualizar

**Comment by aikoncwd** [comment]
Actualmente ha quedado desfasado, se solucionará en la V7
