### ISSUE TITLE
como quitar el cuadradillo de aviso de corriente baja

### ISSUE THREAD

**Issue by ktz69** [aikoncwd/aikoncwd-rpi-mediacenter#52]
pues eso, tengo una tele de plasma y no querria quemar el panel por tener el cuadradito, he pbrobado con un cargador de one plus de 4ah y sigue hay (ninguna relantizacion ni similares)

aver si me puedes ayudar

una pequeña peticion para la proxima version, una opcion de actulizacion 

gracias por tu trabajo, es de lo mejor

**Comment by aikoncwd** [comment]
Hay 2 tipos de cuadraditos:

> Red square: over-temperature
> Rainbow square: under-voltage

Para eliminarlos solo tienes que añadir el parámetro `avoid_warnings` al final del fichero `/boot/config.txt`, tienes 2 valores posibles:

> avoid_warnings=1 removes the warning overlay.
> avoid_warnings=2 additionally allows turbo when low-voltage is present.

Pero lo recomendable es que soluciones ese problema en lugar de esconder el cuadradito de aviso...
