### ISSUE TITLE
Problema con Emulationstation

### ISSUE THREAD

**Issue by Napoleone83** [aikoncwd/aikoncwd-rpi-mediacenter#53]
Hola! primero de todo muchas gracias por este proyecto, es una pasada. 
Escribia porque tengo un problema cuando trato de acceder desde kodi al addon de emulationstation, kodi se cierra, hasta ahi todo normal, pero al arrancar emulationstation, éste se ve como en blanco y negro con toda la pantalla distornionada. como si la configuracion de video no fuera la correcta. Creo intuir en que el problema se encuentra en que tengo la raspberry conectada a una tv de tubo de las antiguas, conectado con un cable rca, e imagino que tendre que modificar algo en la configuración del video. pero en realidad no lo se.  ¿Alguna idea de lo que puede ocurrir?
Gracias y un saludo

**Comment by aikoncwd** [comment]
Edita el fichero `/boot/config.ini` siguiendo la información de [aquí](http://elinux.org/RPiconfig#Video). Deberás usar la opción `hdmi_ignore_hotplug=1` para forzar la salida de vídeo por Cable compuesto/RCA. Luego juega con las resoluciones: 

```
sdtv_mode=0    Normal NTSC
sdtv_mode=1    Japanese version of NTSC – no pedestal
sdtv_mode=2    Normal PAL
sdtv_mode=3    Brazilian version of PAL – 525/60 rather than 625/50, different subcarrier
sdtv_aspect=1  4:3
sdtv_aspect=2  14:9
sdtv_aspect=3  16:9
```
