### ISSUE TITLE
Problema con mando a distancia

### ISSUE THREAD

**Issue by aconur** [aikoncwd/aikoncwd-rpi-mediacenter#56]
Hola buenas. Compre una placa y un mando de control a distancia y tengo un problema. En la pagina (msldigital.com) te enseñan como configurar para que funcione en OpenElec, LibreElec...etc. Pero no explican en ninguno como hacerlo con Raspbian. Tu sabrias mapear y configurarlo todo? Simplemente querria saber que archivos tocastes para mapear el mando de la Xbox por ejemplo. Y enhorabuena por la mediacenter. Funciona absolutamente todo y tienes horas de entretenimiento. Un saludo y gracias por la ayuda

**Comment by aikoncwd** [comment]
Sin conocer el modelo de la placa que has adquirido no podré ayudarte. De todos modos mi consejo es que preguntes al proveedor o fabricante d ela placa (ellos mismos te deberían dar soporte). Si no encuentras nada de forma oficial prueba a buscar en google los conceptos: `"modelo de tu placa"+"raspbian"` a ver si alguien más ha comentado sobre tu problema
