### ISSUE TITLE
Problemas con Exodus

### ISSUE THREAD

**Issue by javier1056** [aikoncwd/aikoncwd-rpi-mediacenter#57]
Buenas tardes. Mi nombre es Javier Ibar y les escribo desde Buenos Aires (Argentina). Tengo funcionando la V6 sobre una Raspberry Pi 3. Tengo el problema que cuando quiera abrir alguna película o serie en Exodus la consola se reinicia por completo cerrando el Kodi volviendo a aparecer las frambuesas del inicio y booteando de nuevo la consola. El problema solo me lo hace con Exodus.
Me podrían ayudar para resolver este problema por favor?

**Comment by javier1056** [comment]
La versión de Exodus que tengo instalada es la 3.1.3 si mal no recuerdo

**Comment by aikoncwd** [comment]
Es muy posible que el contenido que quieras visualizar por Exodus tenga un bitrate mayor (y no soportado por el hardware de la RPi), por eso se reinicia. Lo mejor que puedes hacer es probar algún contenido de calidad inferior o esperar a la actualización de la V7 para ver si se soluciona.

**Comment by javier1056** [comment]
Muchisimas gracias por la respuesta. Te hago una consulta mas. La fecha y hora que me informa el Kodi 16.1 es incorrecta. La cambie en Raspbian pero sigo con el problema en el Kodi. En Kodi tengo configurada la región horaria en Argentina/Buenos Aires.Me podrías ayudar como cambiar la fecha y hora en Kodi por favor?
Saludos y gracias Javier IbarLic. en Sistemas
www.tecnoroot.com.ar
Facebook: Tecno Root
 

    El Viernes, 21 de abril, 2017 10:40:59, AikonCWD <notifications@github.com> escribió:
 

 Es muy posible que el contenido que quieras visualizar por Exodus tenga un bitrate mayor (y no soportado por el hardware de la RPi), por eso se reinicia. Lo mejor que puedes hacer es probar algún contenido de calidad inferior o esperar a la actualización de la V7 para ver si se soluciona.—
