### ISSUE TITLE
No arranca Kodi

### ISSUE THREAD

**Issue by gfuente1978** [aikoncwd/aikoncwd-rpi-mediacenter#58]
Buenos días
He seguido los pasos del tutorial (descargado la imagen, descomprimida con 7z, copiada a la SD con Win32Diskimager) pero al arrancar la Raspberry aparece el garlic-dog, se reinicia y entra en bucle. Todo el rato reinicia, aparece el garlic-dog.
¿Como puedo solucionarlo? ¿Puede ser un problema de la imagen? He comprobado el HASH y es correcto.
He intentado la opción de Verify Only y me da un mensaje de error en el sector 8192.
Gracias!

**Comment by aikoncwd** [comment]
Parece ser que se ha copiado mal la imagen a tu SD... formatea la SD con [SDformatter](https://www.sdcard.org/downloads/formatter_4/) y realiza el proceso de nuevo. Si te sigue fallando es posible que esa SD esté corrompida, prueba con una nueva.
