### ISSUE TITLE
Owncloud

### ISSUE THREAD

**Issue by trepapiedra** [aikoncwd/aikoncwd-rpi-mediacenter#59]
EPA buenas ,ante todo gracias por la pedazo de imagen que te has trabajado.Estoy intentando configurar owncloud ,pero no he sido capaz ,no me deja acceder a la configuración de apache ,alguien ha conseguido instalar alguna cosa similar para poder tener un espacio virtual ?O alguna manera que desde una ubicación fuera de la red local se pueda descargar archivos ?

**Comment by aikoncwd** [comment]
Desde ésta imagen no damos soporte a OwnCloud, prueba a preguntar tu duda en los [foros oficiales de Raspberry](https://www.raspberrypi.org/forums/viewforum.php?f=76), éste tutorial también puede ayudarte: https://pimylifeup.com/raspberry-pi-owncloud/
