### ISSUE TITLE
Distribución Base

### ISSUE THREAD

**Issue by dforce2055** [aikoncwd/aikoncwd-rpi-mediacenter#6]
Hola, felicitaciones por el excelente trabajo.
Me gustaría saber cual es la distribución base que estas utilizando? OpenElec, Xbian?

Gracias por tu tiempo

**Comment by aikoncwd** [comment]
La distribución base es Raspbian Jessie Lite, tiene un repositorio no oficial para instalar Kodi 16.1 y Moonlight, luego he utilizado el Setup-Script de RetroPie para instalar la parte de los emuladores.

Un saludo
