### ISSUE TITLE
Algún tutorial para hacer backup del contenido de un Hdd externo a una nube virtual con rpi???

### ISSUE THREAD

**Issue by rbf0069** [aikoncwd/aikoncwd-rpi-mediacenter#60]
Hola!

Como muchos tengo un HDD externo conectado a la rpi. El caso que pronto tendré una 2ª rpi en otra parte de la casa y me gustaría poder subir todo el contenido del HDD externo a una nube virtual (Tengo acceso a varias ilimitadas, pagando claro está), de forma que además de tener copia de seguridad, me sirva para poder ver con algún addon el contenido en la 2ª rpi.

El caso que leyendo por ahí, todo en inglés, aconsejan rclone porque se puede automatizar y además sube cifrado. Pero no tengo ni idea de como instalar rclone desde consola, he leído en varios sitios y aconsejan descargarlo desde la propia web, pero claro.... no sé si me petará la imagen de aikon que ya me he configurado al gusto y que me gusta como funciona.

La idea sería poder subir el contenido y una vez hecho se automatice y cuando descargue algo nuevo lo suba directamente.

Alguna idea de como hacer esto???

He leído por ahí también montar kodi en windows y mapearlo a través de la red, pero no sé si se refieren a samba, pero claro para luego usar rclone windows me hace falta que esté también en la rpi para que pueda configurarlo :S

Sugerencias?

**Comment by aikoncwd** [comment]
Yo no tengo ni idea de estos temas :(, te recomiendo que traslades tu dudo al foro de soporte oficial de Raspberry: https://www.raspberrypi.org/forums/viewforum.php?f=76
