### ISSUE TITLE
Problemas con fecha y hora en Kodi 16.1

### ISSUE THREAD

**Issue by javier1056** [aikoncwd/aikoncwd-rpi-mediacenter#63]
Los molesto ya que no estoy pudiendo corregir la fecha y hora en mi Kodi 16.1. Tengo una fecha muy vieja y la hora atrasada. Tengo la configuración regional definida como Argentina/Buenos Aires. He probado modificar esto en el Raspbian pero no se refleja en el Kodi.
Me podrían decir como tendría que hacer para modificar la fecha y hora en Kodi?

Saludos y gracias

Javier

**Comment by aikoncwd** [comment]
En el menu preferencias, dentro de Kodi, puedes cambiar la zona horaria: http://kodi.wiki/view/Settings/Appearance

![](https://cdn.htpcbeginner.com/images/2013/12/openelec-set-correct-time-zone.png)
