### ISSUE TITLE
Se me ha actualizado solo Kodi a la 17.0 y no puedo iniciar Desktop!

### ISSUE THREAD

**Issue by Grondoval** [aikoncwd/aikoncwd-rpi-mediacenter#64]
Buenas

No se como al conectar mi raspberry pi despues de un tiempo y reiniciarla, se me ha actualizado Kodi a la versión 17, ahora no me funciona ni Desktop ni EmulationStation... ¿Puede ser porque tenga el wifi de raspberry de forma automática que se conecte si está disponible mi red?

Menos mal que hice copia de seguridad, pero cada vez que la restauro y me da por reiniciar la raspberry se me actualiza Kodi....

¿Que solución podría tener esto?

**Comment by aikoncwd** [comment]
Desconocía que hayan puesto la versión de Kodi 17 en la repo oficial 😮
En cualquier caso deberás esperar a que termine la V7 para solucionar éste problema. Si quieres iniciar el Desktop o Emulationstation puedes hacer lo siguiente:

- Cierra Kodi para salir a la consola
- Escribe el comando `startx` para iniciar el Desktop
- Escribe el comando `emulationstation` para iniciar EmulationStation
