### ISSUE TITLE
Problemas con fecha y hora en Kodi 16.1

### ISSUE THREAD

**Issue by javier1056** [aikoncwd/aikoncwd-rpi-mediacenter#66]
Buen día. Los molesto ya que he cambiado mi zona horario desde las preferencias de Kodi y sigo teniendo el problema que me esta mostrando mal la fecha y la hora. Me esta mostrando el 17/02/2017 y la hora unas 5 horas atrasada.
Desde las preferencias ya configure todo como Argentina/Buenos Aires pero continuo mal con la fecha y hora y por ende cuando quiero abrir por ejemplo Youtube me aparece el error de certificación Ssl por tener mal la fecha.
Me podrían ayudar con esto por favor?. Se puede setear en algún lado la fecha y hora en forma manual?

Saludos y gracias

Javier

**Comment by aikoncwd** [comment]
A parte de configurar la hora en Kodi, necesitas hacerlo en el sistema operativo de Raspbian, cierra Kodi para ir a la consola y escribe `timedatectl set-timezone Europe/Madrid` (evidentemente cambia Europe/Madrid por tu zona horaria. Otra opción es usar el menú de ocnfiguración gráfico: `raspi-config` y utiliza las opciones Internacionales. Un saludo
