### ISSUE TITLE
No puedo grabar la imagen

### ISSUE THREAD

**Issue by Jesuspleomax** [aikoncwd/aikoncwd-rpi-mediacenter#67]
Me podria decir alguien cual es el formato en el que debe de estar la targeta sd para poder grabar la .img?Gracias de antemano
posdata:la estoy grabando en fat32 pero no me la coje y tengo la raspberry pi 3b

**Comment by aikoncwd** [comment]
No necesitas ningún formato. Simplemente formatea tu SD usando [SDformatter](https://www.sdcard.org/downloads/formatter_4/) y luego graba la imagen con [win32diskimage](https://sourceforge.net/projects/win32diskimager/)
