### ISSUE TITLE
Illegal Instruction (core-dumped)

### ISSUE THREAD

**Issue by errepeone** [aikoncwd/aikoncwd-rpi-mediacenter#69]
Descargué la imagen en la versión 6. Al conectar la Rasp puedo ver la imagen del perrito, después del reinicio carga el prompt y se queda en "CARGANDO KODI", luego sale el siguiente error `Illegal Instruction (core-dumped)` y en la siguiente línea me dirije a un log con el supuesto problema. Este es el contenido de uno de los tantos logs que se han creado, al parecer todos contienen lo mismo.

> ############## Kodi CRASH LOG ###############

> 
> ################ SYSTEM INFO ################
>  Date: Tue May 23 06:00:29 CEST 2017
>  Kodi Options: 
>  Arch: armv6l
>  Kernel: Linux 4.4.15+ #897 Tue Jul 12 18:38:58 BST 2016
>  Release: Raspbian GNU/Linux 8 (jessie)
> ############## END SYSTEM INFO ##############
> 
> ############### STACK TRACE #################
> =====>  Core file: /root/core (2017-05-23 06:00:29.805668279 +0200)
>         =========================================
> [New LWP 1323]
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
> Core was generated by `/usr/lib/kodi/kodi.bin --lircdev /var/run/lirc/lircd --standalone'.
> Program terminated with signal SIGILL, Illegal instruction.
> #0  0x0039fbd8 in xbmcutil::GlobalsSingleton<CAdvancedSettings>::getInstance() ()
> 
> Thread 1 (Thread 0xb3e05240 (LWP 1323)):
> #0  0x0039fbd8 in xbmcutil::GlobalsSingleton<CAdvancedSettings>::getInstance() ()
> #1  0x003407a0 in ?? ()
> Backtrace stopped: previous frame identical to this frame (corrupt stack?)
> ############# END STACK TRACE ###############
> 
> ################# LOG FILE ##################
> 
> ﻿23:46:27  16.741259 T:1944781376  NOTICE: special://profile/ is mapped to: special://masterprofile/
> 23:46:27  16.741364 T:1944781376  NOTICE: -----------------------------------------------------------------------
> 23:46:27  16.741407 T:1944781376  NOTICE: Starting Kodi (16.1 Git:2016-04-24-b08ce71-dirty). Platform: Linux ARM 32-bit
> 23:46:27  16.741440 T:1944781376  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
> 23:46:27  16.741478 T:1944781376  NOTICE: Kodi compiled Apr 24 2016 by GCC 4.9.2 for Linux ARM 32-bit version 3.16.7 (200711)
> 23:46:27  16.741642 T:1944781376  NOTICE: Running on Raspbian GNU/Linux 8 (jessie), kernel: Linux ARM 32-bit version 4.4.15-v7+
> 23:46:27  16.741676 T:1944781376  NOTICE: FFmpeg statically linked, version: 2.8.6-kodi-release/2.8-xbmc
> 23:46:27  16.741709 T:1944781376  NOTICE: Host CPU: ARMv7 Processor rev 4 (v7l), 4 cores available
> 23:46:27  16.741737 T:1944781376  NOTICE: ARM Features: Neon enabled
> 23:46:27  16.741770 T:1944781376  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi
> 23:46:27  16.741800 T:1944781376  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/kodi
> 23:46:27  16.741831 T:1944781376  NOTICE: special://masterprofile/ is mapped to: /root/.kodi/userdata
> 23:46:27  16.741861 T:1944781376  NOTICE: special://home/ is mapped to: /root/.kodi
> 23:46:27  16.741892 T:1944781376  NOTICE: special://temp/ is mapped to: /root/.kodi/temp
> 23:46:27  16.741947 T:1944781376  NOTICE: The executable running is: /usr/lib/kodi/kodi.bin
> 23:46:27  16.742014 T:1944781376  NOTICE: Local hostname: mediacenter-v6
> 23:46:27  16.742048 T:1944781376  NOTICE: Log File is located: /root/.kodi/temp/kodi.log
> 23:46:27  16.742096 T:1944781376  NOTICE: -----------------------------------------------------------------------
> 23:46:27  17.063314 T:1944781376   ERROR: DBus: Error org.freedesktop.DBus.Error.InvalidArgs - No such property CanSuspend
> 23:46:27  17.064695 T:1944781376   ERROR: DBus: Error org.freedesktop.DBus.Error.InvalidArgs - No such property CanHibernate
> 23:46:27  17.074333 T:1944781376  NOTICE: load settings...
> 23:46:27  17.228313 T:1944781376  NOTICE: Found 2 Lists of Devices
> 23:46:27  17.228397 T:1944781376  NOTICE: Enumerated PI devices:
> 23:46:27  17.228428 T:1944781376  NOTICE:     Device 1
> 23:46:27  17.228659 T:1944781376  NOTICE:         m_deviceName      : HDMI
> 23:46:27  17.228703 T:1944781376  NOTICE:         m_displayName     : HDMI
> 23:46:27  17.228735 T:1944781376  NOTICE:         m_displayNameExtra:
> 23:46:27  17.228765 T:1944781376  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
> 23:46:27  17.228796 T:1944781376  NOTICE:         m_channels        : FL,FR
> 23:46:27  17.228827 T:1944781376  NOTICE:         m_sampleRates     : 8000,11025,16000,22050,24000,32000,44100,48000,88200,96000,176400,192000
> 23:46:27  17.228859 T:1944781376  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP,AE_FMT_AC3,AE_FMT_DTS,AE_FMT_EAC3
> 23:46:27  17.228903 T:1944781376  NOTICE:     Device 2
> 23:46:27  17.228958 T:1944781376  NOTICE:         m_deviceName      : Analogue
> 23:46:27  17.228989 T:1944781376  NOTICE:         m_displayName     : Analogue
> 23:46:27  17.229019 T:1944781376  NOTICE:         m_displayNameExtra:
> 23:46:27  17.229050 T:1944781376  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
> 23:46:27  17.229078 T:1944781376  NOTICE:         m_channels        : FL,FR
> 23:46:27  17.229109 T:1944781376  NOTICE:         m_sampleRates     : 48000
> 23:46:27  17.229139 T:1944781376  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
> 23:46:27  17.229170 T:1944781376  NOTICE:     Device 3
> 23:46:27  17.229223 T:1944781376  NOTICE:         m_deviceName      : Both
> 23:46:27  17.229254 T:1944781376  NOTICE:         m_displayName     : HDMI and Analogue
> 23:46:27  17.229282 T:1944781376  NOTICE:         m_displayNameExtra:
> 23:46:27  17.229313 T:1944781376  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
> 23:46:27  17.229342 T:1944781376  NOTICE:         m_channels        : FL,FR
> 23:46:27  17.229401 T:1944781376  NOTICE:         m_sampleRates     : 48000
> 23:46:27  17.229433 T:1944781376  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
> 23:46:27  17.229464 T:1944781376  NOTICE: Enumerated ALSA devices:
> 23:46:27  17.229492 T:1944781376  NOTICE:     Device 1
> 23:46:27  17.229548 T:1944781376  NOTICE:         m_deviceName      : @
> 23:46:27  17.229578 T:1944781376  NOTICE:         m_displayName     : Default (bcm2835 ALSA bcm2835 ALSA)
> 23:46:27  17.229609 T:1944781376  NOTICE:         m_displayNameExtra:
> 23:46:27  17.229637 T:1944781376  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
> 23:46:27  17.229668 T:1944781376  NOTICE:         m_channels        : FL,FR
> 23:46:27  17.229698 T:1944781376  NOTICE:         m_sampleRates     : 8000,11025,16000,22050,32000,44100,48000
> 23:46:27  17.229727 T:1944781376  NOTICE:         m_dataFormats     : AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_U8
> 23:46:27  17.272587 T:1944781376  NOTICE: Loaded settings file from special://xbmc/system/advancedsettings.xml
> 23:46:27  17.272873 T:1944781376  NOTICE: Contents of special://xbmc/system/advancedsettings.xml are...
>                                             <?xml version="1.0" encoding="UTF-8" ?>
>                                             <advancedsettings>
>                                               <video>
>                                                 <defaultplayer>dvdplayer</defaultplayer>
>                                                 <defaultdvdplayer>dvdplayer</defaultdvdplayer>
>                                                 <subsdelayrange>120</subsdelayrange>
>                                                 <busydialogdelayms>750</busydialogdelayms>
>                                               </video>
>                                               <fanartres>720</fanartres>
>                                               <imageres>540</imageres>
>                                               <samba>
>                                                 <clienttimeout>30</clienttimeout>
>                                               </samba>
>                                               <network>
>                                                 <readbufferfactor>4.0</readbufferfactor>
>                                                 <cachemembuffersize>31457280</cachemembuffersize>
>                                               </network>
>                                               <gui>
>                                                 <algorithmdirtyregions>3</algorithmdirtyregions>
>                                                 <nofliptimeout>0</nofliptimeout>
>                                               </gui>
>                                               <splash>false</splash>
>                                             </advancedsettings>
> 23:46:27  17.274162 T:1944781376  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
> 23:46:27  17.274200 T:1944781376  NOTICE: Default DVD Player: dvdplayer
> 23:46:27  17.274231 T:1944781376  NOTICE: Default Video Player: dvdplayer
> 23:46:27  17.274261 T:1944781376  NOTICE: Default Audio Player: paplayer
> 23:46:27  17.274298 T:1944781376  NOTICE: Disabled debug logging due to GUI setting. Level 0.
> 23:46:27  17.274328 T:1944781376  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
> 23:46:27  17.274511 T:1944781376  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
> 23:46:27  17.275957 T:1944781376  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
> 23:46:27  17.277451 T:1944781376  NOTICE: Loaded playercorefactory configuration
> 23:46:27  17.277678 T:1944781376  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
> 23:46:27  17.277815 T:1944781376  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
> 23:46:37  18.836382 T:1944781376  NOTICE: Running database version Addons20
> 23:46:37  19.215719 T:1944781376  NOTICE: ADDONS: Using repository repository.shani
> 23:46:37  19.215841 T:1944781376  NOTICE: ADDONS: Using repository repository.xbmc.org
> 23:46:37  19.215876 T:1944781376  NOTICE: ADDONS: Using repository repository.catoal
> 23:46:37  19.215906 T:1944781376  NOTICE: ADDONS: Using repository repository.popcornmix
> 23:46:37  19.215937 T:1944781376  NOTICE: ADDONS: Using repository repository.xbmchub
> 23:46:37  19.215977 T:1944781376  NOTICE: ADDONS: Using repository plugin.video.xbmctorrent
> 23:46:37  19.216007 T:1944781376  NOTICE: ADDONS: Using repository repository.plexus-streams
> 23:46:37  19.216038 T:1944781376  NOTICE: ADDONS: Using repository superrepo.kodi.jarvis.all
> 23:46:37  19.216068 T:1944781376  NOTICE: ADDONS: Using repository repository.quasar
> 23:46:37  19.216099 T:1944781376  NOTICE: ADDONS: Using repository repository.docshadrach
> 23:46:37  19.281628 T:1944781376  NOTICE: Raspberry PI firmware version: Jul 15 2016 17:54:00 
>                                             Copyright (c) 2012 Broadcom
>                                             version efa728fef77ea14ceb1500caf0146395fa282a0f (clean) (release)
> 23:46:37  19.281713 T:1944781376  NOTICE: ARM mem: 752MB GPU mem: 256MB MPG2:1 WVC1:1
> 23:46:37  19.281746 T:1944781376  NOTICE: cacheMemBufferSize: 30MB
> 23:46:37  19.282034 T:1944781376  NOTICE: Config:
>                                             arm_freq=1300
>                                             audio_pwm_mode=1
>                                             avoid_warnings=1
>                                             config_hdmi_boost=5
>                                             core_freq=550
>                                             desired_osc_freq=0x36ee80
>                                             disable_commandline_tags=2
>                                             disable_l2cache=1
>                                             disable_splash=1
>                                             force_eeprom_read=1
>                                             force_pwm_open=1
>                                             framebuffer_ignore_alpha=1
>                                             framebuffer_swap=1
>                                             gpu_freq=550
>                                             h264_freq=350
>                                             hdmi_channel_map=8
>                                             hdmi_drive=2
>                                             hdmi_force_cec_address=65535
>                                             hdmi_force_hotplug=1
>                                             hdmi_ignore_cec_init=1
>                                             init_uart_clock=0x2dc6c00
>                                             initial_turbo=60
>                                             lcd_framerate=60
>                                             over_voltage=6
>                                             over_voltage_avs=0x19f0a
>                                             over_voltage_sdram_c=4
>                                             over_voltage_sdram_i=4
>                                             over_voltage_sdram_p=6
>                                             overscan_bottom=48
>                                             overscan_left=48
>                                             overscan_right=48
>                                             overscan_scale=1
>                                             overscan_top=48
>                                             pause_burst_frames=1
>                                             program_serial_random=1
>                                             sdram_freq=575
>                                             sdram_schmoo=0x2000020
>                                             temp_limit=80
>                                             v3d_freq=500
> 23:46:37  19.282146 T:1944781376  NOTICE: Config:
>                                             decode_MPG2=0x70311cb9
>                                             decode_WVC1=0xb3f61d0c
>                                             device_tree=-
> 23:46:37  19.282202 T:1944781376  NOTICE: InitWindowSystem: Using EGL Implementation: raspberrypi
> 23:46:37  19.283611 T:1944781376  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 60.000000 Hz
> 23:46:37  19.283665 T:1944781376  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 59.940063 Hz
> 23:46:37  19.283703 T:1944781376  NOTICE: Found resolution 800 x 600 for display 0 with 800 x 600 @ 60.000000 Hz
> 23:46:37  19.283739 T:1944781376  NOTICE: Found resolution 800 x 600 for display 0 with 800 x 600 @ 59.940063 Hz
> 23:46:37  19.283775 T:1944781376  NOTICE: Found resolution 1024 x 768 for display 0 with 1024 x 768 @ 60.000000 Hz
> 23:46:37  19.283823 T:1944781376  NOTICE: Found resolution 1024 x 768 for display 0 with 1024 x 768 @ 59.940063 Hz
> 23:46:37  19.283859 T:1944781376  NOTICE: Found resolution 1280 x 1024 for display 0 with 1280 x 1024 @ 60.000000 Hz
> 23:46:37  19.283895 T:1944781376  NOTICE: Found resolution 1280 x 1024 for display 0 with 1280 x 1024 @ 59.940063 Hz
> 23:46:37  19.283932 T:1944781376  NOTICE: Found resolution 720 x 480 for display 0 with 720 x 480 @ 60.000000 Hz
> 23:46:37  19.283976 T:1944781376  NOTICE: Found resolution 720 x 480 for display 0 with 720 x 480 @ 59.940063 Hz
> 23:46:37  19.284012 T:1944781376  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 60.000000 Hz
> 23:46:37  19.284048 T:1944781376  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 59.940063 Hz
> 23:46:37  19.284084 T:1944781376  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 60.000000 Hz
> 23:46:37  19.284121 T:1944781376  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 59.940063 Hz
> 23:46:37  19.284155 T:1944781376  NOTICE: Found resolution 720 x 576 for display 0 with 720 x 576 @ 50.000000 Hz
> 23:46:37  19.284189 T:1944781376  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 50.000000 Hz
> 23:46:37  19.284225 T:1944781376  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 50.000000 Hz
> 23:46:37  19.284262 T:1944781376  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 24.000000 Hz
> 23:46:37  19.284304 T:1944781376  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 23.976025 Hz
> 23:46:37  19.284340 T:1944781376  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 25.000000 Hz
> 23:46:37  19.284376 T:1944781376  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 30.000000 Hz
> 23:46:37  19.284412 T:1944781376  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 29.970032 Hz
> 23:46:37  19.284447 T:1944781376  NOTICE: Found (1920x1080@60.000000) at 28, setting to RES_DESKTOP at 16
> 23:46:37  19.284496 T:1944781376  NOTICE: Checking resolution 16
> 23:46:37  19.388769 T:1944781376  NOTICE: GL_VENDOR = Broadcom
> 23:46:37  19.388859 T:1944781376  NOTICE: GL_RENDERER = VideoCore IV HW
> 23:46:37  19.388891 T:1944781376  NOTICE: GL_VERSION = OpenGL ES 2.0
> 23:46:37  19.388924 T:1944781376  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
> 23:46:37  19.388975 T:1944781376  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_APPLE_rgb_422 GL_EXT_debug_marker
> 23:46:38  19.887362 T:1944781376  NOTICE: Register - new cec device registered on cec->RPI: CEC Adapter (2708:1001)
> 23:46:38  19.948479 T:1944781376  NOTICE: Running database version Addons20
> 23:46:38  19.952415 T:1944781376  NOTICE: Running database version ViewModes6
> 23:46:38  19.960737 T:1944781376  NOTICE: Running database version Textures13
> 23:46:38  19.978590 T:1944781376  NOTICE: Running database version MyMusic56
> 23:46:38  19.994696 T:1944781376  NOTICE: Running database version MyVideos99
> 23:46:38  19.998613 T:1944781376  NOTICE: Running database version TV29
> 23:46:38  20.006491 T:1944781376  NOTICE: Running database version Epg11
> 23:46:38  20.009420 T:1944781376  NOTICE: start dvd mediatype detection
> 23:46:39  20.762550 T:1944781376 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
> 23:46:39  20.847202 T:1944781376  NOTICE: ActiveAE DSP - starting
> 23:46:39  20.860806 T:1944781376  NOTICE: initialize done
> 23:46:39  21.030832 T:1944781376  NOTICE: Running the application...
> 23:46:39  21.435635 T:1944781376  NOTICE: starting zeroconf publishing
> 23:46:39  21.436546 T:1944781376  NOTICE: WebServer: Started the webserver
> 23:46:39  21.436699 T:1944781376  NOTICE: starting upnp client
> 23:46:39  21.462740 T:1595667376  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
> 23:46:39  21.462912 T:1595667376  NOTICE: UDP: Listening on port 9777
> 23:46:39  21.479378 T:1944781376   ERROR: JSONRPC Server: Failed to connect to sdpd
> 23:46:39  21.483292 T:1944781376  NOTICE: Found a joystick : use it as a joystick input device - /dev/input/event0
> 23:46:39  21.542372 T:1944781376  NOTICE: Found a non joystick : use it as standard kodi input device - /dev/input/event1
> 23:46:39  21.672951 T:1568404400  NOTICE: Found a joystick : use it as a joystick input device - /dev/input/event0
> 23:46:39  21.674871 T:1944781376  NOTICE: Enabled Joystick: Xbox Gamepad (userspace driver)
> 23:46:39  21.674959 T:1944781376  NOTICE: Details: Total Axis: 4 Total Hats: 0 Total Buttons: 17
> 23:46:40  22.071217 T:1531863984  NOTICE: [plugin.video.quasar] quasard: starting quasard
> 23:46:40  22.072161 T:1541567408  NOTICE: [plugin.video.quasar] quasar: starting jsonrpc service
> 23:46:41  22.927485 T:1752167344  NOTICE: service.libraryautoupdate-0.9.8 : Update Library Service starting...
> 23:46:41  22.939386 T:1752167344  NOTICE: service.libraryautoupdate-0.9.8 : update timers
> 23:46:41  22.944550 T:1752167344  NOTICE: service.libraryautoupdate-0.9.8 : Creating timer for Video Library
> 23:46:42  24.346264 T:1531863984  NOTICE: [plugin.video.quasar] Deleting stale files set([])
> 23:46:43  24.977972 T:1531863984  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0m
> 23:46:43  24.978809 T:1531863984  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0m________
> 23:46:43  24.983496 T:1531863984  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0m\_____  \  __ _______    ___________ _______
> 23:46:43  24.984447 T:1531863984  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0m /  / \  \|  |  \__  \  /  ___/\__  \\_  __ \
> 23:46:43  24.985039 T:1531863984  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0m/   \_/.  \  |  // __ \_\___ \  / __ \|  | \/
> 23:46:43  24.985529 T:1531863984  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0m\_____\ \_/____/(____  /____  >(____  /__|
> 23:46:43  24.988947 T:1531863984  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0m       \__>          \/     \/      \/
> 23:46:43  24.989563 T:1531863984  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0m
> 23:46:43  24.990509 T:1531863984  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0mVersion: "v0.9.34" Go: go1.6.2
> 23:46:43  24.991226 T:1531863984  NOTICE: [plugin.video.quasar] INFO  config       ▶ Reload           [0mReloading configuration...
> 23:46:43  25.405054 T:1531863984  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0mAddon: plugin.video.quasar v0.9.34
> 23:46:43  25.452696 T:1531863984  NOTICE: [plugin.video.quasar] INFO  btservice    ▶ configure        [0mSetting Session settings...
> 23:46:43  25.457088 T:1531863984  NOTICE: [plugin.video.quasar] INFO  btservice    ▶ configure        [0mSetting Encryption settings...
> 23:46:43  25.458309 T:1531863984  NOTICE: [plugin.video.quasar] INFO  btservice    ▶ alertsConsumer   [0mConsuming alerts...
> 23:46:43  25.458878 T:1531863984  NOTICE: [plugin.video.quasar] INFO  tmdb         ▶ CheckApiKey      [0mChecking TMDB API key...
> 23:46:44  25.748987 T:1531863984  NOTICE: [plugin.video.quasar] [32mNOTI  tmdb         ▶ CheckApiKey      [0mTMDB API key check passed, using ae4bd1b...
> 23:46:44  25.769651 T:1531863984  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0mUpdating Kodi Addon Repositories
> 23:46:44  25.783670 T:1541567408  NOTICE: [plugin.video.quasar] Resetting RPC objects...
> 23:46:47  29.309328 T:1531863984  NOTICE: [plugin.video.quasar] INFO  repository   ▶ GetAddonFiles    [0mRequest for: addons.xml.md5
> 23:46:48  30.440208 T:1531863984  NOTICE: [plugin.video.quasar] INFO  repository   ▶ getLastRelease   [0mGetting latest main release
> 23:46:48  30.583784 T:1531863984  NOTICE: [plugin.video.quasar] INFO  repository   ▶ getLastRelease   [0mLast release: v0.9.34 on master
> 23:46:49  31.219238 T:1531863984  NOTICE: [plugin.video.quasar] INFO  repository   ▶ getLastRelease   [0mGetting latest main release
> 23:46:49  31.363487 T:1531863984  NOTICE: [plugin.video.quasar] INFO  repository   ▶ getLastRelease   [0mLast release: v0.9.34 on master
> 23:46:49  31.580702 T:1531863984  NOTICE: [plugin.video.quasar] INFO  repository   ▶ fetchChangelog   [0mFetching add-on changelog...
> 23:46:50  31.742292 T:1568404400  NOTICE: Found a joystick : use it as a joystick input device - /dev/input/event0
> 23:46:50  32.189968 T:1531863984  NOTICE: [plugin.video.quasar] [GIN] 2016/07/20 - 21:46:50 |[97;42m 200 [0m|   2.88073945s | ::1 |[97;44m  [0m GET     /repository/scakemyer/plugin.video.quasar/addons.xml.md5
> 23:46:52  34.458000 T:1944781376  NOTICE: Storing total System Uptime
> 23:46:52  34.458282 T:1944781376  NOTICE: Saving settings
> 23:46:52  34.468918 T:1944781376  NOTICE: stop all
> 23:46:52  34.469471 T:1944781376  NOTICE: stop player
> 23:46:52  34.469597 T:1944781376  NOTICE: ES: Stopping event server
> 23:46:52  34.469669 T:1944781376  NOTICE: stopping upnp
> 23:46:52  34.473671 T:1595667376  NOTICE: ES: UDP Event server stopped
> 23:46:52  34.620667 T:1944781376  NOTICE: stopping zeroconf publishing
> 23:46:52  34.627953 T:1944781376  NOTICE: WebServer: Stopped the webserver
> 23:46:52  34.628063 T:1944781376  NOTICE: stop dvd detect media
> 23:46:55  37.393974 T:1944781376  NOTICE: stop sap announcement listener
> 23:46:55  37.394112 T:1944781376  NOTICE: clean cached files!
> 23:46:55  37.394184 T:1944781376  NOTICE: unload skin
> 23:46:55  37.426613 T:1944781376 WARNING: Cleanup: Having to cleanup texture pointer-nofocus.png
> 23:46:55  37.427319 T:1944781376 WARNING: Cleanup: Having to cleanup texture pointer-focus.png
> 23:46:55  37.427418 T:1944781376 WARNING: Cleanup: Having to cleanup texture pointer-focus-drag.png
> 23:46:55  37.427494 T:1944781376 WARNING: Cleanup: Having to cleanup texture pointer-focus-click.png
> 23:46:58  40.068554 T:1531863984  NOTICE: [plugin.video.quasar] INFO  main         ▶ func1            [0mShutting down...
> 23:46:58  40.069767 T:1531863984  NOTICE: [plugin.video.quasar] INFO  btservice    ▶ Close            [0mStopping BT Services...
> 23:46:58  40.071384 T:1531863984  NOTICE: [plugin.video.quasar] INFO  main         ▶ func1            [0mBye bye
> 23:46:58  40.151848 T:1778783152  NOTICE: [plugin.video.quasar] quasard: exiting quasard daemon
> 23:46:58  40.152805 T:1778783152  NOTICE: [plugin.video.quasar] quasard: quasard daemon exited
> 23:46:58  40.154140 T:1701573552  NOTICE: [plugin.video.quasar] quasar: exiting quasard
> 23:46:59  40.862244 T:1541567408  NOTICE: [plugin.video.quasar] quasar: exiting jsonrpc service
> 23:46:59  41.162506 T:1944781376  NOTICE: stopped
> 23:46:59  41.162663 T:1944781376  NOTICE: destroy
> 23:46:59  41.170685 T:1944781376  NOTICE: closing down remote control service
> 23:46:59  41.170998 T:1944781376  NOTICE: unload sections
> 23:46:59  41.190079 T:1944781376  NOTICE: special://profile/ is mapped to: special://masterprofile/
> 23:46:59  41.392868 T:1944781376  NOTICE: destroy
> 23:46:59  41.393093 T:1944781376 WARNING: Attempted to remove window 10013 from the window manager when it didn't exist
> 23:46:59  41.393169 T:1944781376 WARNING: Attempted to remove window 10014 from the window manager when it didn't exist
> 23:46:59  41.393238 T:1944781376 WARNING: Attempted to remove window 10015 from the window manager when it didn't exist
> 23:46:59  41.393360 T:1944781376 WARNING: Attempted to remove window 10016 from the window manager when it didn't exist
> 23:46:59  41.393429 T:1944781376 WARNING: Attempted to remove window 10017 from the window manager when it didn't exist
> 23:46:59  41.393494 T:1944781376 WARNING: Attempted to remove window 10018 from the window manager when it didn't exist
> 23:46:59  41.393562 T:1944781376 WARNING: Attempted to remove window 10019 from the window manager when it didn't exist
> 23:46:59  41.393627 T:1944781376 WARNING: Attempted to remove window 10021 from the window manager when it didn't exist
> 23:46:59  41.393692 T:1944781376 WARNING: Attempted to remove window 10107 from the window manager when it didn't exist
> 23:46:59  41.393753 T:1944781376 WARNING: Attempted to remove window 10115 from the window manager when it didn't exist
> 23:46:59  41.393818 T:1944781376 WARNING: Attempted to remove window 10104 from the window manager when it didn't exist
> 23:46:59  41.393883 T:1944781376  NOTICE: closing down remote control service
> 23:46:59  41.393951 T:1944781376  NOTICE: unload sections
> 23:46:59  41.394043 T:1944781376  NOTICE: application stopped...
> 
> 
> ############### END LOG FILE ################
> 
> ############ END Kodi CRASH LOG #############

He montado la SD en una RPI 2 B+

**Comment by aikoncwd** [comment]
Para RPi 2B tendrás que actualizar el sistema previamente:

    apt-get update
    apt-get upgrade
    apt-get dist-upgrade
    rpi-update
    reboot

Un saludo
