### ISSUE TITLE
Problema con Kodi

### ISSUE THREAD

**Issue by david19dh** [aikoncwd/aikoncwd-rpi-mediacenter#72]
Ante todo darte las gracias por este estupendo proyecto. Te cuento lo que me sucede. Actualicé el script de retropie a la última versión y desde entonces en Kodi me falla todo. No me carga ni adryan, ni plexus. Tampoco va el acceso directo a Retropie.
 ¿Alguna idea?

**Comment by david19dh** [comment]
Esto está ya solucionado. Reinicié y volvió a funcionar adryan y plexus.

**Comment by lluiscanals** [comment]
Buenas @david19dh si ya lo solucionaste, puedes cerrar el ticket?
Gracais!
