### ISSUE TITLE
Problema con mando Ps3

### ISSUE THREAD

**Issue by JaviVargas** [aikoncwd/aikoncwd-rpi-mediacenter#8]
Al iniciar con un mando de ps3 conectado por usb a la rpi 2 parece ser que da error al arrancar kodi, lo cual hace que se quede la pantalla en negro. Cada 30 segundos aprox. intenta abrir de nuevo kodi ocurriendo lo mismo hasta que se desconecte el mando.

Un saludo!

**Comment by aikoncwd** [comment]
Hola, es muy posible que sea un fallo de Kodi al cargar el driver del mando PS3... prueba a deshabilitar el soporte de gamepads/controllers en Kodi, limitando así el uso de tu mando PS3 a RetroPie, mira ésta guía para saber el menú de Kodi y deshabilitarlo

[aqui](http://kodi.wiki/view/HOW-TO:Configure_controllers)

Cierro el ticket, si sigues con error abre uno nuevo :)
