### ISSUE TITLE
Me gustaria cambiar la imagen del garlic-doc

### ISSUE THREAD

**Issue by elroger** [aikoncwd/aikoncwd-rpi-mediacenter#9]
Excelente trabajo! Gracias por tu esfuerzo, me gustaria saber como puedo cambiar la imagen del garlic-doc. Un saludo!

**Comment by aikoncwd** [comment]
Si mal no recuerdo (te lo digo de memoria) la foto está en `/etc/splash.jpg`

**Comment by elroger** [comment]
Justo, que buena memoria, muchas gracias!

**Comment by aikoncwd** [comment]
Cierro el ticket :)
